### ISSUE TITLE
Can't bind to 'mobxAutorun' since it isn't a known property of 'ng-container' After Angular update

### ISSUE THREAD

**Issue by phmello** [CirclonGroup/angular-tree-component#510]
I just updated my angular to the latest version

Angular CLI: 1.6.1
Node: 8.3.0
OS: win32 x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.0.1
@angular/cli: 1.6.1
@angular/flex-layout: 2.0.0-beta.10-4905443
@angular/material: 5.0.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
typescript: 2.6.2
webpack: 3.10.0

 Error: Template parse errors:
        Can't bind to 'mobxAutorun' since it isn't a known property of 'ng-container'.
        1. If 'mobxAutorun' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
        2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
            <ng-container [ERROR ->]*mobxAutorun="{dontDetach: true}">
              <div
                *ngIf="!templates.treeNodeFullTemplate"
        "): ng:///TreeModule/TreeNodeComponent.html@1:18
        Property binding mobxAutorun not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
            [ERROR ->]<ng-container *mobxAutorun="{dontDetach: true}">
              <div
                *ngIf="!templates.treeNodeFullTem"): ng:///TreeModule/TreeNodeComponent.html@1:4
            at syntaxError c:/dev/portal-b2b/node_modules/@angular/compiler/esm5/compiler.js:485:22)
            at TemplateParser.webpackJsonp.../../../compiler/esm5/compiler.js.TemplateParser.parse c:/dev/portal-b2b/node_modules/@angular/compiler/esm5/compiler.js:24631:1)
            at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._parseTemplate c:/dev/portal-b2b/node_modules/@angular/compiler/esm5/compiler.js:34442:1)
            at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileTemplate c:/dev/portal-b2b/node_modules/@angular/compiler/esm5/compiler.js:34417:1)
            at http://localhost:9876/_karma_webpack_/webpack:/c:/dev/portal-b2b/node_modules/@angular/compiler/esm5/compiler.js:34318:48
            at Set.forEach (<anonymous>)
            at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileComponents c:/dev/portal-b2b/node_modules/@angular/compiler/esm5/compiler.js:34318:1)
            at http://localhost:9876/_karma_webpack_/webpack:/c:/dev/portal-b2b/node_modules/@angular/compiler/esm5/compiler.js:34206:1
            at Object.then c:/dev/portal-b2b/node_modules/@angular/compiler/esm5/compiler.js:474:33)
            at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndAllComponents c:/dev/portal-b2b/node_modules/@angular/compiler/esm5/compiler.js:34204:1)

**Comment by gaop** [comment]
check mobx and mobx-angular (at dir node_modules) if low version? try upgrade them 'npm install mobx mobx-angular'

**Comment by adamkleingit** [comment]
Maybe remove node_modules and reinstall


*Adam Klein*
*Chief Technology Officer*



*Tel.*   +972-52-7475633 <+972527475633>
*Web*  500tech.com <http://www.500tech.com/> | github.com/500tech |
@adamklein500 <http://twitter.com/adamklein500>

**Comment by phmello** [comment]
First thing I've done, error still happening

**Comment by adamkleingit** [comment]
Can you reproduce here?
https://plnkr.co/edit/u5fMmaM14rJ0aqG3k240?p=preview

**Comment by Hotzilla** [comment]
Facing the same issue. Started after latest version. I will try to provide more info and way to reproduce.

**Comment by sugaryy** [comment]
I have the same problem.

**Comment by closer27** [comment]
is there anyone who resolved this problem? TT

**Comment by elixiao** [comment]
This issue caused by angular-tree-component use old version of mobx, try solve it by

```
npm install --save mobx-angular mobx
```

then remove folder `project_root/node_modules/angular-tree-component/node_modules`

**Comment by tobiasengelhardt** [comment]
Closing this issue due to inactivity. Please open a new issue if the problem still exists.
