### ISSUE TITLE
"No provider for TreeModel" in Angular Universal

### ISSUE THREAD

**Issue by Ventzy** [CirclonGroup/angular-tree-component#657]
Not sure what is the problem, as the tree seems to be working in my simple setup, although I get following exception on server side - Angular Universal, Angular 6. There is no such error in the browser - outside of universal.
```
ERROR { Error: Uncaught (in promise): Error: StaticInjectorError(AppServerModule)[TreeVirtualScroll -> TreeModel]:
  StaticInjectorError(Platform: core)[TreeVirtualScroll -> TreeModel]:
    NullInjectorError: No provider for TreeModel!
Error: StaticInjectorError(AppServerModule)[TreeVirtualScroll -> TreeModel]:
  StaticInjectorError(Platform: core)[TreeVirtualScroll -> TreeModel]:
    NullInjectorError: No provider for TreeModel!
    at NullInjector.get (C:\ngu\dist\server.js:4948:19)
    at resolveToken (C:\ngu\dist\server.js:5186:24)
    at tryResolveToken (C:\ngu\dist\server.js:5130:16)
    at StaticInjector.get (C:\ngu\dist\server.js:5027:20)
    at resolveToken (C:\ngu\dist\server.js:5186:24)
    at tryResolveToken (C:\ngu\dist\server.js:5130:16)
    at StaticInjector.get (C:\ngu\dist\server.js:5027:20)
    at resolveNgModuleDep (C:\ngu\dist\server.js:12262:29)
    at NgModuleRef_.get (C:\ngu\dist\server.js:12950:16)
    at resolveDep (C:\ngu\dist\server.js:13315:45)
    at resolvePromise (C:\ngu\dist\server.js:937:31)
    at resolvePromise (C:\ngu\dist\server.js:894:17)
    at C:\ngu\dist\server.js:996:17
    at ZoneDelegate.invokeTask (C:\ngu\dist\server.js:544:31)
    at Object.onInvokeTask (C:\ngu\dist\server.js:7701:33)
    at ZoneDelegate.invokeTask (C:\ngu\dist\server.js:543:36)
    at Zone.runTask (C:\ngu\dist\server.js:311:47)
    at drainMicroTaskQueue (C:\ngu\dist\server.js:718:35)
    at ZoneTask.invokeTask (C:\ngu\dist\server.js:623:21)
    at Server.ZoneTask.invoke (C:\ngu\dist\server.js:608:48)
  rejection:
   { Error: StaticInjectorError(AppServerModule)[TreeVirtualScroll -> TreeModel]:
  StaticInjectorError(Platform: core)[TreeVirtualScroll -> TreeModel]:
    NullInjectorError: No provider for TreeModel!
    at NullInjector.get (C:\ngu\dist\server.js:4948:19)
    at resolveToken (C:\ngu\dist\server.js:5186:24)
    at tryResolveToken (C:\ngu\dist\server.js:5130:16)
    at StaticInjector.get (C:\ngu\dist\server.js:5027:20)
    at resolveToken (C:\ngu\dist\server.js:5186:24)
    at tryResolveToken (C:\ngu\dist\server.js:5130:16)
    at StaticInjector.get (C:\ngu\dist\server.js:5027:20)
    at resolveNgModuleDep (C:\ngu\dist\server.js:12262:29)
    at NgModuleRef_.get (C:\ngu\dist\server.js:12950:16)
    at resolveDep (C:\ngu\dist\server.js:13315:45)
     ngTempTokenPath: null,
     ngTokenPath: [ 'TreeVirtualScroll', [Object] ] },
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value: { Error: StaticInjectorError(AppServerModule)[TreeVirtualScroll -> TreeModel]:
  StaticInjectorError(Platform: core)[TreeVirtualScroll -> TreeModel]:
    NullInjectorError: No provider for TreeModel!
    at NullInjector.get (C:\ngu\dist\server.js:4948:19)
    at resolveToken (C:\ngu\dist\server.js:5186:24)
    at tryResolveToken (C:\ngu\dist\server.js:5130:16)
    at StaticInjector.get (C:\ngu\dist\server.js:5027:20)
    at resolveToken (C:\ngu\dist\server.js:5186:24)
    at tryResolveToken (C:\ngu\dist\server.js:5130:16)
    at StaticInjector.get (C:\ngu\dist\server.js:5027:20)
    at resolveNgModuleDep (C:\ngu\dist\server.js:12262:29)
    at NgModuleRef_.get (C:\ngu\dist\server.js:12950:16)
    at resolveDep (C:\ngu\dist\server.js:13315:45) ngTempTokenPath: null, ngTokenPath: [A
rray] } },
```

Steps to reproduce:

1. Download Universal https://angular.io/generated/zips/universal/universal.zip
2. Run it
```
npm install
npm run build:ssr
npm run serve:ssr
```
At this point it should show dashboard without issues at  http://localhost:4000/dashboard

3. Setup angular-tree-component
```
npm install --save angular-tree-component

# Add:
# In app.module.ts
TreeModule.forRoot(),
# In dashboard.component.html
<tree-root [nodes]="nodes" [options]="options"></tree-root>
# In dashboard.component.ts
  nodes = [
    {
      id: 1,
      name: 'root1',
      children: [
        { id: 2, name: 'child1' },
        { id: 3, name: 'child2' }
      ]
    },
    {
      id: 4,
      name: 'root2',
      children: [
        { id: 5, name: 'child2.1' },
        {
          id: 6,
          name: 'child2.2',
          children: [
            { id: 7, name: 'subsub' }
          ]
        }
      ]
    }
  ];
  options= {};
```
4. Run again and reload http://localhost:4000/dashboard
```
npm run build:ssr
npm run serve:ssr

> angular-io-example@1.0.0 serve:ssr C:\ngu
> node dist/server.js

Node server listening on http://localhost:4000
Running on the server with appId=tour-of-heroes
ERROR { Error: Uncaught (in promise): Error: StaticInjectorError(AppServerModule)[TreeVirtualScroll -> TreeModel]:
...
[full error trace above]
```

**Comment by JuliaRakitina** [comment]
Same issue

**Comment by debender495** [comment]
is this in the spec file?

**Comment by tobiasengelhardt** [comment]
Closing this issue due to inactivity. Please open a new issue if the problem still exists.
