### ISSUE TITLE
Error during compiling

### ISSUE THREAD

**Issue by gmaggiodev** [CirclonGroup/angular-tree-component#734]
Cloning the reporitory and trying to compile with command `npm run example:cli:win` (no change to the code) I receive this error:
`
ERROR in ./src/styles.css (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./src/styles.css)
Module build failed: Error: Can't resolve 'angular-tree-component/dist/angular-tree-component.css' in 'D:\code\GitHub\angular-tree-component\example\cli\src'
    at doResolve (D:\code\GitHub\angular-tree-component\example\cli\node_modules\enhanced-resolve\lib\Resolver.js:180:19)
    at hook.callAsync (D:\code\GitHub\angular-tree-component\example\cli\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (D:\code\GitHub\angular-tree-component\example\cli\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (D:\code\GitHub\angular-tree-component\example\cli\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)
    at hook.callAsync (D:\code\GitHub\angular-tree-component\example\cli\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (D:\code\GitHub\angular-tree-component\example\cli\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (D:\code\GitHub\angular-tree-component\example\cli\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (D:\code\GitHub\angular-tree-component\example\cli\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (D:\code\GitHub\angular-tree-component\example\cli\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)
    at hook.callAsync (D:\code\GitHub\angular-tree-component\example\cli\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn5 (eval at create (D:\code\GitHub\angular-tree-component\example\cli\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:57:1)
    at resolver.doResolve (D:\code\GitHub\angular-tree-component\example\cli\node_modules\enhanced-resolve\lib\ModuleKindPlugin.js:23:37)
    at hook.callAsync (D:\code\GitHub\angular-tree-component\example\cli\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn0 (eval at create (D:\code\GitHub\angular-tree-component\example\cli\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (D:\code\GitHub\angular-tree-component\example\cli\node_modules\enhanced-resolve\lib\Resolver.js:238:5)
    at _fn1 (eval at create (D:\code\GitHub\angular-tree-component\example\cli\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:24:1)
`
# Additional Info
Windows 10
npm 6.1.0
node 9.8.0

**Comment by tobiasengelhardt** [comment]
We updated the commands in the newest version. Please open a new issue if the problem still exists.
